# Generated by Django 3.2.5 on 2022-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='comments',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='auto',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
    ]
