# Generated by Django 3.2.5 on 2022-04-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20220402_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter a make (e.g. Dodge)', max_length=40, validators=[django.core.validators.MinLengthValidator(2, message='Make must be greater than 1 character')]),
        ),
    ]
